### ISSUE TITLE
adding @tomato42 as maintainer, moving project to 'tlsfuzzer'

### ISSUE THREAD

**Issue by warner** [tlsfuzzer/python-ecdsa#226]
Hey folks, just wanted to let everyone know that Hubert Kario (aka @tomato42) has agreed to take over maintenance of python-ecdsa. It's probably obvious to everyone that I haven't had time for it, and it lines up with other projects that he's working on.

We'll be moving this repository out of `warner/python-ecdsa` and into the new https://github.com/tlsfuzzer umbrella organization, where we can share admin acccess to it.

**Comment by tomato42** [comment]
I'm assigning it to myself, as I'll update the links in badges in README, in the documentation, and setup.py.

**Comment by tomato42** [comment]
As far as maintenance of the project goes, I was de-facto maintainer for the past year, so nothing much in practice will change (except URLs and fixing the CI integrations).

@warner you should be able to verify that you have admin access to this repo now.
