### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by iceman1001** [tlsfuzzer/python-ecdsa#246]
Hey,

Installed on Ubunutu 20.04 with `python3 -m pip install ecdsa`   where  `version 0.16.1` gets installed.
I noticed you added some smaller curves later,  which leads me to ask when is the next release planned?

**Comment by tomato42** [comment]
I'd like to at least fix the bugs tagged for 0.17.0: https://github.com/tlsfuzzer/python-ecdsa/milestone/6

**Comment by iceman1001** [comment]
yeah,  good features to have in that milestone.  The documentation gets me all the time now when I have tried your module.

Meanwhile,  a minor 0.16.2  release ?

**Comment by tomato42** [comment]
I use semantic versioning, new curves means current master doesn't qualify for 0.16.2
and even without them, I don't want to release a new version without #214 getting fixed
