### ISSUE TITLE
what is the encoding scheme of the generated shared secret

### ISSUE THREAD

**Issue by kphf1995cm** [tlsfuzzer/python-ecdsa#248]

**Comment by tomato42** [comment]
there are two methods, `generate_sharedsecret_bytes`:
https://github.com/tlsfuzzer/python-ecdsa/blob/8dea392e9cc43d2f909a5283234679b921f0db94/src/ecdsa/ecdh.py#L293-L304

and `generate_sharedsecret`:
https://github.com/tlsfuzzer/python-ecdsa/blob/8dea392e9cc43d2f909a5283234679b921f0db94/src/ecdsa/ecdh.py#L310-L325

the first one returns `bytes` the latter an `int`; there is no encoding to them, if you want them hex or base64 encoded, you'll need to do it yourself; but then any normal cryptographic protocol will want the shared secret as `bytes`, as it will feed it into some hash or KDF...

**Comment by tomato42** [comment]
@kphf1995cm please close the issue if my comment answers your question.

**Comment by kphf1995cm** [comment]
OK！
--
 况鹏
    Peng Kuang
 清华大学 网络科学与网络空间研究院
    Tel： +86 18292886592
    ***@***.***


发件人: Hubert Kario
发送时间: 2021年4月22日 2:30
收件人: tlsfuzzer/python-ecdsa
抄送: echorez; Mention
主题: Re: [tlsfuzzer/python-ecdsa] what is the encoding scheme of thegenerated shared secret (#248)

@kphf1995cm please close the issue if my comment answers your question.
