### ISSUE TITLE
Do not use the commented code in ecdsa.py in a production environment -- The problem with random number k

### ISSUE THREAD

**Issue by 99Kies** [tlsfuzzer/python-ecdsa#275]
![image](https://user-images.githubusercontent.com/45918704/144787728-41043748-030f-4ffb-9971-4aad942a3711.png)

**For developers:**

  Please do not use Python's Random library as your dependency for generating K. (If a random number is used unsecurely during signature, the key may be leaked.)

**For a better solution:**

  RFC6979 is preferred here <https://www.rfc-editor.org/rfc/inline-errata/rfc6979.html>

**An example of the Bitcoin curve:**

  <https://github.com/99Kies/ecdsa/blob/main/ecdsa.py#L250>

**Comment by tomato42** [comment]
It's not using Python's Random, it's using SystemRandom, see lines 15 and 16 in your screenshot.
Also, you absolutely *SHOULD NOT* use those low level interfaces, you should use `SigningKey.sign()` for signing data.

Or, if you want to use RFC 6979, you should use `sign_deterministic()`:
https://github.com/tlsfuzzer/python-ecdsa/blob/b3b27cd4811ce935e42bbcd251206ff2cb3b51b9/src/ecdsa/keys.py#L1355-L1400
or `sign_digest_deterministic()`:
https://github.com/tlsfuzzer/python-ecdsa/blob/b3b27cd4811ce935e42bbcd251206ff2cb3b51b9/src/ecdsa/keys.py#L1418-L1461
