### ISSUE TITLE
NIST256p sextuple is wrong?

### ISSUE THREAD

**Issue by TigerZhao007** [tlsfuzzer/python-ecdsa#286]
# NIST256p,(aka secp256r1, prime256v1 and NIST P-256)
from ecdsa import NIST256p

parameter a = -3, 
b = 41058363725152142129326129780047268409114441015993725554835256314039467401291

However, according to 
https://neuromancer.sk/std/secg/secp256r1
a = 0xffffffff00000001000000000000000000000000fffffffffffffffffffffffc
  =  115792089210356248762697446949407573530086143415290314195533631308867097853948
b = 0x5ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b
  = 41058363725152142129326129780047268409114441015993725554835256314039467401291

why a is not the same ?

**Comment by tomato42** [comment]
-3 mod 0xffffffff00000001000000000000000000000000ffffffffffffffffffffffff == 0xffffffff00000001000000000000000000000000fffffffffffffffffffffffc
