### ISSUE TITLE
Example sharing request

### ISSUE THREAD

**Issue by reist2002** [tlsfuzzer/python-ecdsa#295]
Good day.
Your ECDSA implementation is very fast, but unfortunately my Python skills are not enough to find solution in the module dependencies. There is no problem with the pure mathematics of elliptic curves for me.
Could you please provide a simple low-level example of using your project? Determination of points by their Jacobi coordinates for the secp256k1 curve and their addition function?

**Comment by tomato42** [comment]
You mean how to add two points on secp256k1 when you have their Jacobi coordinates?

**Comment by reist2002** [comment]
Yes. And get the third point as a result of adding them.

**Comment by reist2002** [comment]
Yes, this is exactly what I needed. Thank you.
