### ISSUE TITLE
unused parameter 'order' in sigdecode_der(sig_der, order)

### ISSUE THREAD

**Issue by opacey** [tlsfuzzer/python-ecdsa#318]
The 'order' parameter is not used in this function:
`def sigdecode_der(sig_der, order):`
...within ecdsa/util.py

I believe curve group order is not relevant to this function so could be removed for clarity.

**Comment by tomato42** [comment]
PR with doc updates welcome, but I think the module description for util.py makes it rather clear:
https://github.com/tlsfuzzer/python-ecdsa/blob/2457dc7c9b7337edcb868a323c5b648a32da2b8c/src/ecdsa/util.py#L2-L11
