### ISSUE TITLE
DER parser is probably wrong

### ISSUE THREAD

**Issue by vporton** [tlsfuzzer/python-ecdsa#332]
Either this package or DFINITY Internet Identity is buggy:

https://forum.dfinity.org/t/why-does-the-internet-identity-der-key-not-work-in-python/27174

**Comment by tomato42** [comment]
I don't know what (1, 3, 6, 1, 4, 1, 56387, 1, 2) OID is for, but it isn't associated with any regular ECDSA or EdDSA keys.
