### ISSUE TITLE
RFE: drop use `six` and python<=3.7

### ISSUE THREAD

**Issue by kloczek** [tlsfuzzer/python-ecdsa#335]
Python 2.x has been EOSed +4 years ago. Last year python 3.7 support has been EOSed and this year end of Sep python 3.8 will be EOSed.
Because of above I think that it would be good start thinking about drop support for all those versions by:
- release all already committed changes as new version (0.18.1?) (any plans to do that soon? 🤔 https://github.com/tlsfuzzer/python-ecdsa/compare/python-ecdsa-0.18.0...master shows +90 commits since last release)
- mark that version as last version which supports python<=3.7
- with flushed all currently committed changes on top of new version can be created branch like 0.18.x on which will be committed any changes which will maintain that legacy support if someone still will need python<=3.7 support.

Simple it is better to have clean code on the master instead in one source tree maintain multiple version.
I can share part of my work on that goal as draft PR if you want.

**Comment by kloczek** [comment]
Actually I've started my work from last release and just found that some work dropping python<=3.7 support has been done 😋 (which is good 😄 ).
Will back soon with some results after check what already is on master.

**Comment by kloczek** [comment]
> Python 2 will be supported as long as there's a supported RHEL version that uses python 2 by default.

I did not propose stop supporting python 2 at all but only keep that support outside of master (on branch).

What about release new version? 🤔

**Comment by kloczek** [comment]
BTW .. from https://access.redhat.com/solutions/4455511
> The [RHEL 8 AppStream Lifecycle Page](https://access.redhat.com/node/4079021) puts the end date of RHEL 8's Python 2.7 package at June 2024.

So it is only few weeks so IMPO it make sense to start preparing for that 😋

**Comment by tomato42** [comment]
Have you considered not telling people how they should develop software when the only reason for the request is some kind of personal vendetta against `six` or Python 2.7?

We've already been through this discussion in #304. This is your final warning, stop this behaviour or I'll block you from contributing to this project.

**Comment by kloczek** [comment]
> We've already been through this discussion in #304. This is your final warning, stop this behaviour or I'll block you from contributing to this project.

Do you really remember all what you wrote ~two years ago? 🤔 
(please do not start from argmentum ad personam)
Python 2.xaready is EOSed +4 years. Is it not time to start clean the code?
